export interface FormDataI{
   description:string
   hero_title:string  
   hero_image:string
   hero_logo:string
   service_title:string
   service_description:string
   service_image:string
   service_one_title:string
   service_one_description:string
   service_one_image:string
   service_two_title:string
   service_two_description:string
   service_two_image:string
   service_three_title:string
   service_three_description:string
   service_three_image:string
   service_four_title:string
   service_four_description:string
   service_four_image:string
   service_five_title:string
   service_five_description:string
   service_five_image:string
   service_six_title:string
   service_six_description:string
   service_six_image:string
   gallery_title:string
   gallery_file_one:string
   gallery_file_two:string
   gallery_file_three:string
   gallery_file_four:string
   gallery_file_five:string
   gallery_file_six:string
   contact_title:string
   contact_description:string
  }
  